env:
  node: true
  browser: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 7
  sourceType: module
plugins:
  - react
parser: babel-eslint
rules:
  import/no-named-as-default: off
  import/prefer-default-export: off
  jsx-a11y/anchor-is-valid:
    - error
    - components:
        - Link
      specialLink:
        - to
  react/jsx-curly-newline: off
  react/jsx-filename-extension:
    - error
    - extensions:
        - .js
  react/require-default-props: off
  react/no-did-mount-set-state: off
  react/default-props-match-prop-types: off
  react/destructuring-assignment: off
  react/jsx-one-expression-per-line: off
  react/jsx-wrap-multilines: off
  react/sort-comp: off
  react/no-access-state-in-setstate: warn
  react/no-unused-prop-types: warn
  react/prop-types: off
  react/jsx-props-no-spreading: off
  react/jsx-fragments: warn
  react/static-property-placement: off
  react/state-in-constructor: off
  react/no-deprecated: warn
